
openapi: 3.0.0
info:
  title: Certificate External API For DFSP Participants
  version: "1.0"
  description: API for fetching certificates from outside DFSP Participants.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:3220/
    description: Local server

paths:
  /certs/{certId}:
    get:
      tags:
        - GET
      summary: Get a specific certificate
      parameters:
        - name: certId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the certificate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Certificate'
        '404':
          description: Certificate not found

components:
  schemas:
    Certificate:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
