
openapi: 3.0.0
info:
  title: Certificate Management API
  version: "1.0"
  description: API for managing certificates in the Mojaloop ecosystem.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:3200/
    description: Local server

paths:
  /certs/{participantId}:
    get:
      tags:
        - GET
      summary: Get a specific certificate
      parameters:
        - name: participantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the certificate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Certificate'
        '404':
          description: Certificate not found
  /certs:
    post:
      tags:
        - POST
      summary: Store a new certificate
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCertificate'
      responses:
        '200':
          description: Certificate stored successfully

  /certs/file:
    post:
      tags:
        - POST
      summary: Store a new certificate file
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                participantId:
                  type: string
                  description: The ID of the certificate
                cert:
                  type: string
                  format: binary
                  description: The certificate file
      responses:
        '200':
          description: Certificate file stored successfully
        '400':
          description: Invalid input

  /certs/{participantId}/approve:
    post:
      tags:
        - POST
      summary: Approve a certificate
      security:
        - bearerAuth: []
      parameters:
        - name: participantId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Certificate approved successfully
        '400':
          description: Bad request (e.g., missing participantId, trying to approve own certificate)
        '404':
          description: Certificate not found
        '500':
          description: Error approving certificate

components:
  schemas:
    Certificate:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
    NewCertificate:
      type: object
      properties:
        participantId:
          type: string
          example: 'dfsp1'
        cert:
          type: string
          example: |
            -----BEGIN CERTIFICATE-----
            MIICyDCCAbCgAwIBAgIUMjAwMDEwMDAwMDAxMDAwMDAwMDMwDQYJKoZIhvcNAQEL
            BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIwMDUxNzE5MjY0NVoXDTIxMDUx
            NzE5MjY0NVowFDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgk
            -----END CERTIFICATE-----

security:
  - bearerAuth: []
